language: c
sudo: false

branches:
  only:
    - master

install:
    - source devtools/travis-ci/install_miniconda.sh
    - conda config --add channels omnia

script:
    conda build --quiet devtools/conda-recipe
    && devtools/travis-ci/build_docs.sh

env:
    matrix:
        - CONDA_PY=2.7
        - CONDA_PY=3.5

deploy:
    - provider: s3
      access_key_id:
        secure: ""
      secrete_access_key:
        secure: ""
      bucket: "msmbuilder.org"
      upload-dir: osprey
      skip_cleanup: true
      local_dir: docs/_deploy/
      on:
          branch: master
          condition: "$CONDA_PY = 3.5"
