package:
  name: osprey
  version: "0.4"

source:
  fn: osprey-0.4.tar.gz
  url: https://pypi.python.org/packages/source/o/osprey/osprey-0.4.tar.gz
  md5: 76c9f4467490f80d2d5d0536c47de296
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - osprey = osprey:main
    #
    # Would create an entry point called osprey that calls osprey.main()

    - osprey = osprey.cli.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - osprey
    - osprey.cli
    - osprey.plugins
    - osprey.plugins.tests
    - osprey.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - osprey --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pandegroup/osprey
  license: Apache Software License
  summary: '|Build Status| |PyPi version| |Supported Python versions| |License|\n|Documentation Status|'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
