package:
  name: osprey
  version: "1.1.0dev0"

source:
  path: ../../

build:
  entry_points:
    - osprey = osprey.cli.main:main
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - pyyaml
    - numpy
    - scipy
    - scikit-learn
    - sqlalchemy
    - bokeh
    - matplotlib

test:

  requires:
    - nose
    - nose-timer
    - gpy
    - msmbuilder
    - mdtraj
    - coverage
    - python-coveralls



  imports:
    - osprey
    - osprey.cli
    - osprey.plugins
    - osprey.plugins.tests
    - osprey.tests

  commands:
    - osprey --help
    - nosetests -v osprey --with-timer --with-coverage  --cover-package=osprey

about:
  home: https://github.com/msmbuilder/osprey
  license: Apache Software License
  summary: 'Run distributed cross-validation'

# vim: ts=2 sw=2 et
